NAME = fillit
CC = gcc
FLAGS = -Wall -Wextra -Werror
HEAD = 
SRC = 
OBJ = $(SRC:.c=.o)

all: $(NAME)

$(NAME): $(OBJ)
	$(CC) $^ $(FLAGS) -o $@

%.o: %.c $(HEAD)
	$(CC) $< $(FLAGS) -o $@

clean:
	rm -f $(OBJ)

fclean: clean
	rm -f $(NAME)

re: fclean all

.PHONY: all clean fclean re
